
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (49518, 'de', 'AF', 'Afrika', 'RW', 'Ruanda');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (51537, 'de', 'AF', 'Afrika', 'SO', 'Somalia');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (69543, 'de', 'AS', 'Asien', 'YE', 'Jemen');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (99237, 'de', 'AS', 'Asien', 'IQ', 'Irak');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (102358, 'de', 'AS', 'Asien', 'SA', 'Saudi-Arabien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (130758, 'de', 'AS', 'Asien', 'IR', 'Iran (Islamische Republik)');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (146669, 'de', 'EU', 'Europa', 'CY', 'Zypern');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (149590, 'de', 'AF', 'Afrika', 'TZ', 'Tansania');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (163843, 'de', 'AS', 'Asien', 'SY', 'Syrien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (174982, 'de', 'AS', 'Asien', 'AM', 'Armenien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (192950, 'de', 'AF', 'Afrika', 'KE', 'Kenia');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (203312, 'de', 'AF', 'Afrika', 'CD', 'Kongo');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (223816, 'de', 'AF', 'Afrika', 'DJ', 'Dschibuti');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (226074, 'de', 'AF', 'Afrika', 'UG', 'Uganda');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (239880, 'de', 'AF', 'Afrika', 'CF', 'Zentralafrikanische Republik');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (241170, 'de', 'AF', 'Afrika', 'SC', 'Seychellen');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (248816, 'de', 'AS', 'Asien', 'JO', 'Jordanien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (272103, 'de', 'AS', 'Asien', 'LB', 'Libanon');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (285570, 'de', 'AS', 'Asien', 'KW', 'Kuwait');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (286963, 'de', 'AS', 'Asien', 'OM', 'Oman');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (289688, 'de', 'AS', 'Asien', 'QA', 'Katar');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (290291, 'de', 'AS', 'Asien', 'BH', 'Bahrain');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (290557, 'de', 'AS', 'Asien', 'AE', 'Vereinigte Arabische Emirate');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (294640, 'de', 'AS', 'Asien', 'IL', 'Israel');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (298795, 'de', 'AS', 'Asien', 'TR', 'Türkei');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (337996, 'de', 'AF', 'Afrika', 'ET', 'Äthiopien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (338010, 'de', 'AF', 'Afrika', 'ER', 'Eritrea');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (357994, 'de', 'AF', 'Afrika', 'EG', 'Ägypten');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (366755, 'de', 'AF', 'Afrika', 'SD', 'Sudan');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (390903, 'de', 'EU', 'Europa', 'GR', 'Griechenland');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (433561, 'de', 'AF', 'Afrika', 'BI', 'Burundi');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (453733, 'de', 'EU', 'Europa', 'EE', 'Estland');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (458258, 'de', 'EU', 'Europa', 'LV', 'Lettland');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (587116, 'de', 'AS', 'Asien', 'AZ', 'Aserbaidschan');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (597427, 'de', 'EU', 'Europa', 'LT', 'Litauen');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (607072, 'de', 'EU', 'Europa', 'SJ', 'Svalbard und Jan Mayen');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (614540, 'de', 'AS', 'Asien', 'GE', 'Georgien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (617790, 'de', 'EU', 'Europa', 'MD', 'Moldau (Republik Moldau)');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (630336, 'de', 'EU', 'Europa', 'BY', 'Weißrussland');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (660013, 'de', 'EU', 'Europa', 'FI', 'Finnland');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (661882, 'de', 'EU', 'Europa', 'AX', 'Alandinseln');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (690791, 'de', 'EU', 'Europa', 'UA', 'Ukraine');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (718075, 'de', 'EU', 'Europa', 'MK', 'Ehemalige jugoslawische Republik Mazedonien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (719819, 'de', 'EU', 'Europa', 'HU', 'Ungarn');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (732800, 'de', 'EU', 'Europa', 'BG', 'Bulgarien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (783754, 'de', 'EU', 'Europa', 'AL', 'Albanien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (798544, 'de', 'EU', 'Europa', 'PL', 'Polen');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (798549, 'de', 'EU', 'Europa', 'RO', 'Rumänien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (831053, 'de', 'EU', 'Europa', 'XK', 'Kosovo');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (878675, 'de', 'AF', 'Afrika', 'ZW', 'Simbabwe');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (895949, 'de', 'AF', 'Afrika', 'ZM', 'Sambia');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (921929, 'de', 'AF', 'Afrika', 'KM', 'Komoren');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (927384, 'de', 'AF', 'Afrika', 'MW', 'Malawi');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (932692, 'de', 'AF', 'Afrika', 'LS', 'Lesotho');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (933860, 'de', 'AF', 'Afrika', 'BW', 'Botswana');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (934292, 'de', 'AF', 'Afrika', 'MU', 'Mauritius');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (934841, 'de', 'AF', 'Afrika', 'SZ', 'Swasiland');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (935317, 'de', 'AF', 'Afrika', 'RE', 'Réunion');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (953987, 'de', 'AF', 'Afrika', 'ZA', 'Südafrika');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1024031, 'de', 'AF', 'Afrika', 'YT', 'Mayotte');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1036973, 'de', 'AF', 'Afrika', 'MZ', 'Mosambik');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1062947, 'de', 'AF', 'Afrika', 'MG', 'Madagaskar');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1149361, 'de', 'AS', 'Asien', 'AF', 'Afghanistan');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1168579, 'de', 'AS', 'Asien', 'PK', 'Pakistan');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1210997, 'de', 'AS', 'Asien', 'BD', 'Bangladesch');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1218197, 'de', 'AS', 'Asien', 'TM', 'Turkmenistan');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1220409, 'de', 'AS', 'Asien', 'TJ', 'Tadschikistan');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1227603, 'de', 'AS', 'Asien', 'LK', 'Sri Lanka');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1252634, 'de', 'AS', 'Asien', 'BT', 'Bhutan');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1269750, 'de', 'AS', 'Asien', 'IN', 'Indien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1282028, 'de', 'AS', 'Asien', 'MV', 'Malediven');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1282588, 'de', 'AS', 'Asien', 'IO', 'Britisches Territorium im Indischen Ozean');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1282988, 'de', 'AS', 'Asien', 'NP', 'Nepal');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1327865, 'de', 'AS', 'Asien', 'MM', 'Birma (Myanmar)');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1512440, 'de', 'AS', 'Asien', 'UZ', 'Usbekistan');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1522867, 'de', 'AS', 'Asien', 'KZ', 'Kasachstan');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1527747, 'de', 'AS', 'Asien', 'KG', 'Kirgistan');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1546748, 'de', 'AN', 'Antarktis', 'TF', 'Französische Süd- und Antarktisgebiete');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1547376, 'de', 'AS', 'Asien', 'CC', 'Kokosinseln');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1559582, 'de', 'OC', 'Ozeanien', 'PW', 'Palau');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1562822, 'de', 'AS', 'Asien', 'VN', 'Vietnam');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1605651, 'de', 'AS', 'Asien', 'TH', 'Thailand');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1643084, 'de', 'AS', 'Asien', 'ID', 'Indonesien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1655842, 'de', 'AS', 'Asien', 'LA', 'Laos');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1668284, 'de', 'AS', 'Asien', 'TW', 'Taiwan');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1694008, 'de', 'AS', 'Asien', 'PH', 'Philippinen');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1733045, 'de', 'AS', 'Asien', 'MY', 'Malaysia');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1814991, 'de', 'AS', 'Asien', 'CN', 'China');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1819730, 'de', 'AS', 'Asien', 'HK', 'Hongkong');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1820814, 'de', 'AS', 'Asien', 'BN', 'Brunei');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1821275, 'de', 'AS', 'Asien', 'MO', 'Macau');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1831722, 'de', 'AS', 'Asien', 'KH', 'Kambodscha');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1835841, 'de', 'AS', 'Asien', 'KR', 'Südkorea');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1861060, 'de', 'AS', 'Asien', 'JP', 'Japan');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1873107, 'de', 'AS', 'Asien', 'KP', 'Nordkorea');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1880251, 'de', 'AS', 'Asien', 'SG', 'Singapur');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1899402, 'de', 'OC', 'Ozeanien', 'CK', 'Cookinseln');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (1966436, 'de', 'OC', 'Ozeanien', 'TL', 'Timor-Leste');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2017370, 'de', 'EU', 'Europa', 'RU', 'Russland');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2029969, 'de', 'AS', 'Asien', 'MN', 'Mongolei');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2077456, 'de', 'OC', 'Ozeanien', 'AU', 'Australien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2078138, 'de', 'AS', 'Asien', 'CX', 'Weihnachtsinsel');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2080185, 'de', 'OC', 'Ozeanien', 'MH', 'Marshall-Inseln');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2081918, 'de', 'OC', 'Ozeanien', 'FM', 'Mikronesien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2088628, 'de', 'OC', 'Ozeanien', 'PG', 'Papua-Neuguinea');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2103350, 'de', 'OC', 'Ozeanien', 'SB', 'Solomon-Inseln');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2110297, 'de', 'OC', 'Ozeanien', 'TV', 'Tuwalu');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2110425, 'de', 'OC', 'Ozeanien', 'NR', 'Nauru');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2134431, 'de', 'OC', 'Ozeanien', 'VU', 'Vanuatu');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2139685, 'de', 'OC', 'Ozeanien', 'NC', 'Neukaledonien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2155115, 'de', 'OC', 'Ozeanien', 'NF', 'Norfolkinsel');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2186224, 'de', 'OC', 'Ozeanien', 'NZ', 'Neuseeland');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2205218, 'de', 'OC', 'Ozeanien', 'FJ', 'Fidschi');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2215636, 'de', 'AF', 'Afrika', 'LY', 'Libysch-Arabische Dschamahirija');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2233387, 'de', 'AF', 'Afrika', 'CM', 'Kamerun');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2245662, 'de', 'AF', 'Afrika', 'SN', 'Senegal');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2260494, 'de', 'AF', 'Afrika', 'CG', 'Kongo (Republik Kongo)');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2264397, 'de', 'EU', 'Europa', 'PT', 'Portugal');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2275384, 'de', 'AF', 'Afrika', 'LR', 'Liberia');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2287781, 'de', 'AF', 'Afrika', 'CI', 'Elfenbeinküste');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2300660, 'de', 'AF', 'Afrika', 'GH', 'Ghana');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2309096, 'de', 'AF', 'Afrika', 'GQ', 'Äquatorialguinea');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2328926, 'de', 'AF', 'Afrika', 'NG', 'Nigeria');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2361809, 'de', 'AF', 'Afrika', 'BF', 'Burkina Faso');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2363686, 'de', 'AF', 'Afrika', 'TG', 'Togo');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2372248, 'de', 'AF', 'Afrika', 'GW', 'Guinea-Bissau');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2378080, 'de', 'AF', 'Afrika', 'MR', 'Mauretanien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2395170, 'de', 'AF', 'Afrika', 'BJ', 'Benin');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2400553, 'de', 'AF', 'Afrika', 'GA', 'Gabun');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2403846, 'de', 'AF', 'Afrika', 'SL', 'Sierra Leone');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2410758, 'de', 'AF', 'Afrika', 'ST', 'Sao Tomé und Principe');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2411586, 'de', 'EU', 'Europa', 'GI', 'Gibraltar');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2413451, 'de', 'AF', 'Afrika', 'GM', 'Gambia');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2420477, 'de', 'AF', 'Afrika', 'GN', 'Guinea');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2434508, 'de', 'AF', 'Afrika', 'TD', 'Tschad');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2440476, 'de', 'AF', 'Afrika', 'NE', 'Niger');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2453866, 'de', 'AF', 'Afrika', 'ML', 'Mali');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2464461, 'de', 'AF', 'Afrika', 'TN', 'Tunesien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2510769, 'de', 'EU', 'Europa', 'ES', 'Spanien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2542007, 'de', 'AF', 'Afrika', 'MA', 'Marokko');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2562770, 'de', 'EU', 'Europa', 'MT', 'Malta');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2589581, 'de', 'AF', 'Afrika', 'DZ', 'Algerien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2622320, 'de', 'EU', 'Europa', 'FO', 'Färöer-Inseln');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2623032, 'de', 'EU', 'Europa', 'DK', 'Dänemark');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2629691, 'de', 'EU', 'Europa', 'IS', 'Island');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2635167, 'de', 'EU', 'Europa', 'GB', 'Vereinigtes Königreich');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2658434, 'de', 'EU', 'Europa', 'CH', 'Schweiz');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2661886, 'de', 'EU', 'Europa', 'SE', 'Schweden');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2750405, 'de', 'EU', 'Europa', 'NL', 'Niederlande');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2782113, 'de', 'EU', 'Europa', 'AT', 'Österreich');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2802361, 'de', 'EU', 'Europa', 'BE', 'Belgien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2921044, 'de', 'EU', 'Europa', 'DE', 'Deutschland');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2960313, 'de', 'EU', 'Europa', 'LU', 'Luxemburg');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2963597, 'de', 'EU', 'Europa', 'IE', 'Irland');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (2993457, 'de', 'EU', 'Europa', 'MC', 'Monaco');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3017382, 'de', 'EU', 'Europa', 'FR', 'Frankreich');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3041565, 'de', 'EU', 'Europa', 'AD', 'Andorra');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3042058, 'de', 'EU', 'Europa', 'LI', 'Liechtenstein');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3042142, 'de', 'EU', 'Europa', 'JE', 'Jersey');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3042225, 'de', 'EU', 'Europa', 'IM', 'Insel Man');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3042362, 'de', 'EU', 'Europa', 'GG', 'Guernsey');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3057568, 'de', 'EU', 'Europa', 'SK', 'Slowakei (Slowakische Republik)');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3077311, 'de', 'EU', 'Europa', 'CZ', 'Tschechien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3144096, 'de', 'EU', 'Europa', 'NO', 'Norwegen');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3164670, 'de', 'EU', 'Europa', 'VA', 'Staat der Vatikanstadt');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3168068, 'de', 'EU', 'Europa', 'SM', 'San Marino');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3175395, 'de', 'EU', 'Europa', 'IT', 'Italien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3190538, 'de', 'EU', 'Europa', 'SI', 'Slowenien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3194884, 'de', 'EU', 'Europa', 'ME', 'Montenegro');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3202326, 'de', 'EU', 'Europa', 'HR', 'Kroatien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3277605, 'de', 'EU', 'Europa', 'BA', 'Bosnien und Herzegowina');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3351879, 'de', 'AF', 'Afrika', 'AO', 'Angola');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3355338, 'de', 'AF', 'Afrika', 'NA', 'Namibia');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3370751, 'de', 'AF', 'Afrika', 'SH', 'St. Helena');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3374084, 'de', 'NA', 'Nordamerika', 'BB', 'Barbados');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3374766, 'de', 'AF', 'Afrika', 'CV', 'Kap Verde');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3378535, 'de', 'SA', 'Südamerika', 'GY', 'Guyana');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3381670, 'de', 'SA', 'Südamerika', 'GF', 'Französisch-Guayana');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3382998, 'de', 'SA', 'Südamerika', 'SR', 'Suriname');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3424932, 'de', 'NA', 'Nordamerika', 'PM', 'St. Pierre und Miquelon');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3425505, 'de', 'NA', 'Nordamerika', 'GL', 'Grönland');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3437598, 'de', 'SA', 'Südamerika', 'PY', 'Paraguay');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3439705, 'de', 'SA', 'Südamerika', 'UY', 'Uruguay');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3469034, 'de', 'SA', 'Südamerika', 'BR', 'Brasilien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3474414, 'de', 'SA', 'Südamerika', 'FK', 'Falklandinseln');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3474415, 'de', 'AN', 'Antarktis', 'GS', 'Südgeorgien und die Südlichen Sandwichinseln');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3489940, 'de', 'NA', 'Nordamerika', 'JM', 'Jamaika');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3508796, 'de', 'NA', 'Nordamerika', 'DO', 'Dom. Republik');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3562981, 'de', 'NA', 'Nordamerika', 'CU', 'Kuba');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3570311, 'de', 'NA', 'Nordamerika', 'MQ', 'Martinique');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3572887, 'de', 'NA', 'Nordamerika', 'BS', 'Bahamas');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3573345, 'de', 'NA', 'Nordamerika', 'BM', 'Bermuda');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3573511, 'de', 'NA', 'Nordamerika', 'AI', 'Anguilla');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3573591, 'de', 'NA', 'Nordamerika', 'TT', 'Trinidad und Tobago');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3575174, 'de', 'NA', 'Nordamerika', 'KN', 'Saint Kitts und Nevis');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3575830, 'de', 'NA', 'Nordamerika', 'DM', 'Dominica');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3576396, 'de', 'NA', 'Nordamerika', 'AG', 'Antigua und Barbuda');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3576468, 'de', 'NA', 'Nordamerika', 'LC', 'St. Lucia');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3576916, 'de', 'NA', 'Nordamerika', 'TC', 'Turks- und Caicosinseln');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3577279, 'de', 'NA', 'Nordamerika', 'AW', 'Aruba');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3577718, 'de', 'NA', 'Nordamerika', 'VG', 'Britische Jungferninseln');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3577815, 'de', 'NA', 'Nordamerika', 'VC', 'St. Vincent und die Grenadinen');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3578097, 'de', 'NA', 'Nordamerika', 'MS', 'Montserrat');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3578421, 'de', 'NA', 'Nordamerika', 'MF', 'St. Martin');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3578476, 'de', 'NA', 'Nordamerika', 'BL', 'St. Barthélemy');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3579143, 'de', 'NA', 'Nordamerika', 'GP', 'Guadeloupe');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3580239, 'de', 'NA', 'Nordamerika', 'GD', 'Grenada');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3580718, 'de', 'NA', 'Nordamerika', 'KY', 'Kaimaninseln');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3582678, 'de', 'NA', 'Nordamerika', 'BZ', 'Belize');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3585968, 'de', 'NA', 'Nordamerika', 'SV', 'El Salvador');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3595528, 'de', 'NA', 'Nordamerika', 'GT', 'Guatemala');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3608932, 'de', 'NA', 'Nordamerika', 'HN', 'Honduras');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3617476, 'de', 'NA', 'Nordamerika', 'NI', 'Nikaragua');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3624060, 'de', 'NA', 'Nordamerika', 'CR', 'Costa Rica');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3625428, 'de', 'SA', 'Südamerika', 'VE', 'Venezuela');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3658394, 'de', 'SA', 'Südamerika', 'EC', 'Ecuador');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3686110, 'de', 'SA', 'Südamerika', 'CO', 'Kolumbien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3703430, 'de', 'NA', 'Nordamerika', 'PA', 'Panama');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3723988, 'de', 'NA', 'Nordamerika', 'HT', 'Haiti');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3865483, 'de', 'SA', 'Südamerika', 'AR', 'Argentinien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3895114, 'de', 'SA', 'Südamerika', 'CL', 'Chile');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3923057, 'de', 'SA', 'Südamerika', 'BO', 'Bolivien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3932488, 'de', 'SA', 'Südamerika', 'PE', 'Peru');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (3996063, 'de', 'NA', 'Nordamerika', 'MX', 'Mexiko');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (4030656, 'de', 'OC', 'Ozeanien', 'PF', 'Französisch-Polynesien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (4030699, 'de', 'OC', 'Ozeanien', 'PN', 'Pitcairn');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (4030945, 'de', 'OC', 'Ozeanien', 'KI', 'Kiribati');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (4031074, 'de', 'OC', 'Ozeanien', 'TK', 'Tokelau');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (4032283, 'de', 'OC', 'Ozeanien', 'TO', 'Tonga');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (4034749, 'de', 'OC', 'Ozeanien', 'WF', 'Wallis und Futuna');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (4034894, 'de', 'OC', 'Ozeanien', 'WS', 'Samoa');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (4036232, 'de', 'OC', 'Ozeanien', 'NU', 'Niue');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (4041468, 'de', 'OC', 'Ozeanien', 'MP', 'Nördliche Marianen');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (4043988, 'de', 'OC', 'Ozeanien', 'GU', 'Guam');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (4566966, 'de', 'NA', 'Nordamerika', 'PR', 'Puerto Rico');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (4796775, 'de', 'NA', 'Nordamerika', 'VI', 'Amerikanische Jungferninseln');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (5854968, 'de', 'OC', 'Ozeanien', 'UM', 'Amerikanisch-Ozeanien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (5880801, 'de', 'OC', 'Ozeanien', 'AS', 'Amerikanisch-Samoa');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (6251999, 'de', 'NA', 'Nordamerika', 'CA', 'Kanada');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (6252001, 'de', 'NA', 'Nordamerika', 'US', 'USA');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (6254930, 'de', 'AS', 'Asien', 'PS', 'Palästinensische Autonomiegebiete');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (6255147, 'de', 'AS', 'Asien', NULL, NULL);
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (6255148, 'de', 'EU', 'Europa', NULL, NULL);
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (6290252, 'de', 'EU', 'Europa', 'RS', 'Serbien');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (6697173, 'de', 'AN', 'Antarktis', 'AQ', 'Antarktis');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (7609695, 'de', 'NA', 'Nordamerika', 'SX', 'Sint Maarten');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (7626836, 'de', 'NA', 'Nordamerika', 'CW', 'Curaçao');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (7626844, 'de', 'NA', 'Nordamerika', 'BQ', 'Bonaire');
INSERT INTO geoip.geoip_locations_temp (geoname_id, locale_code, continent_code, continent_name, country_iso_code, country_name) VALUES (7909807, 'de', 'AF', 'Afrika', 'SS', 'Südsudan');


-- Completed on 2016-11-17 13:53:56

--
-- PostgreSQL database dump complete
--

